$CYA1 = "The following hostnames should be included in this report, if they are not then port 135 is being blocked to XYZ client from auw2toolsn001p."
$WEX_OnPrem = "WEX OnPrem =         aue1cvault000p, pwm-wex-5035, pwm-wex-5036, pwm-wex-5206 and pwm-wex-5222"
$WEX_CoreServices = "WEX CoreServices =   auw2cvaultx000p, auw2cvaultx001p, aws-wex-5269 and aws-wex-5270"
$WEX_SecureCoreProd = "WEX SecureCoreProd = AUW2CVAULTU000P, AUW2CVAULTU001P, aws-wex-5281 and aws-wex-5282"
$WEX_EFSPRod = "EFS PROD =            aue1cvault001p, aue1cvault002p, auw2cvault000p and auw2cvault001p"
$IFCS_CoreServicesProd = "IFCS CoreServicesProd = aec1cmvs000p and aec1cmvs003p"
$IFCS_IFCSProd = "IFCS IFCSProd =        aec1cmvs001p, aec1cmvs006p and asg1cmvs004p"
$WEX_Infrastructure = "WEX Infrastructure = auw2toolsn001p"
$BlankLine = ""
$Header = "HostName`t`t`t`t`tDrive`tTotalCap`tFreeCap`t`tUsedCap"

Add-Content D:\CommVault\DriveSpaceChecker\DriveSpace.txt $CYA1
Add-Content D:\CommVault\DriveSpaceChecker\DriveSpace.txt $BlankLine
Add-Content D:\CommVault\DriveSpaceChecker\DriveSpace.txt $WEX_OnPrem
Add-Content D:\CommVault\DriveSpaceChecker\DriveSpace.txt $WEX_CoreServices
Add-Content D:\CommVault\DriveSpaceChecker\DriveSpace.txt $WEX_SecureCoreProd
Add-Content D:\CommVault\DriveSpaceChecker\DriveSpace.txt $WEX_EFSProd
Add-Content D:\CommVault\DriveSpaceChecker\DriveSpace.txt $BlankLine
Add-Content D:\CommVault\DriveSpaceChecker\DriveSpace.txt $IFCS_CoreServicesProd
Add-Content D:\CommVault\DriveSpaceChecker\DriveSpace.txt $IFCS_IFCSProd
Add-Content D:\CommVault\DriveSpaceChecker\DriveSpace.txt $BlankLine
Add-Content D:\CommVault\DriveSpaceChecker\DriveSpace.txt $WEX_Infrastructure
Add-Content D:\CommVault\DriveSpaceChecker\DriveSpace.txt $BlankLine
Add-Content D:\CommVault\DriveSpaceChecker\DriveSpace.txt $BlankLine
Add-Content D:\CommVault\DriveSpaceChecker\DriveSpace.txt $Header



$ArrComputers = "aue1cvault000p.wexprodr.wexglobal.com","pwm-wex-5035.ad.wrightexpress.com","pwm-wex-5036.ad.wrightexpress.com","pwm-wex-5206.ad.wrightexpress.com","pwm-wex-5222.ad.wrightexpress.com","auw2cvaultx000p.wexprodr.wexglobal.com","auw2cvaultx001p.wexprodr.wexglobal.com","aws-wex-5269.ad.wrightexpress.com","aws-wex-5270.ad.wrightexpress.com","AUW2CVAULTU000P.WEXPRODR.WEXGLOBAL.COM","AUW2CVAULTU001P.WEXPRODR.WEXGLOBAL.COM","aws-wex-5281.ad.wrightexpress.com","aws-wex-5282.ad.wrightexpress.com","aue1cvault001p.wexprodr.wexglobal.com","aue1cvault002p.wexprodr.wexglobal.com","auw2cvault000p.wexprodr.wexglobal.com","auw2cvault001p.wexprodr.wexglobal.com","aec1cmvs000p.wexprodr.wexglobal.com","aec1cmvs003p.wexprodr.wexglobal.com","aec1cmvs001p.wexprodr.wexglobal.com","aec1cmvs006p.wexprodr.wexglobal.com","asg1cmvs004p.wexprodr.wexglobal.com","auw2toolsn001p.wexprodr.wexglobal.com"


foreach ($Computer in $ArrComputers) 
{
    $DiskReport = Get-WmiObject Win32_logicaldisk -ComputerName $Computer | Select-Object DeviceID,Size,FreeSpace
    $ArrDrive = $DiskReport.DeviceID
   
    foreach ($DriveLtr in $ArrDrive.Split("U+0020"))
    {
        $disk = ([wmi]"\\$Computer\root\cimv2:Win32_logicalDisk.DeviceID='$DriveLtr'")
        
        $TotalCap = [Math]::ROUND($disk.Size/1024/1024/1024)
        $FreeCap = [Math]::ROUND($disk.FreeSpace/1024/1024/1024)
        $UsedCap = [Math]::ROUND(($disk.Size-$disk.FreeSpace)/1024/1024/1024)

        $OutPut = "$Computer`t`t$DriveLtr`t$TotalCap`t`t$FreeCap`t`t$UsedCap"
        Add-Content D:\CommVault\DriveSpaceChecker\DriveSpace.txt $OutPut
    }
   $EmptyOut = "`n"
   Add-Content D:\CommVault\DriveSpaceChecker\DriveSpace.txt $EmptyOut
}

$CurrentDate = Get-Date -Format g

$FromAddress = "donotreply@wexinc.com"
$ToAddress = "_6d996@WrightExpress.com"
$MessageSubject = "CommVault Server Drive Space Utilization, generated by auw2tools001p"
$MessageBody = "Open Attachment"
$SendingServer = "smtp-relay.wexinc.com"
$Attachment = "D:\CommVault\DriveSpaceChecker\DriveSpace.txt"

#Send the message
Send-MailMessage -To $ToAddress -From $FromAddress -Subject $MessageSubject -Body $MessageBody -SmtpServer $SendingServer -Attachments $Attachment